### ISSUE TITLE
SafariのZenzawatchで視聴すると設定の項目が表示されない

### ISSUE THREAD

**Issue by na7na7nananana7** [kPherox/ZenzaWatch#26]
開発者御中

開発お疲れ様です。いつも使わせていただいております。
以下の環境においてZenzaWatchで視聴するとChromeでは表示された設定の項目がなく、いろいろと変更ができないのですが仕様でしょうか。
ブラウザ: Safari
拡張機能: Tampermonkey
ZenzaWatch用スクリプト: 
[ZenzaWatch-dev.user.js](https://github.com/kphrx/ZenzaWatch/blob/playlist-deploy/dist/ZenzaWatch-dev.user.js)
[ZenzaHLS.user.js](https://github.com/kphrx/ZenzaWatch/blob/playlist-deploy/dist/ZenzaHLS.user.js)

NGユーザーやコメントは登録できるのに、削除ができないので一方通行なので誤登録で一生表示されなくなります
仕様であれば諦めますので使用せず視聴を行うつもりです。

**Comment by kphrx** [comment]
2.6.3-fix-playlist.24 で修正リリース予定です

75d19f3

変更前
![image](https://user-images.githubusercontent.com/13777426/188140351-1b630cbc-b67a-46e7-bc6b-71963007b019.png)

変更後
![image](https://user-images.githubusercontent.com/13777426/188140269-a42a2250-aa64-4cfd-a664-a0714be461c7.png)
