### ISSUE TITLE
無料期間の過ぎた動画をdアニメストアの動画に置き換える機能が機能していない

### ISSUE THREAD

**Issue by nonamestreamer** [kPherox/ZenzaWatch#45]
2.6.3-fix-playlist.44
を使用していますがこの機能をオンにしても「この動画は有料です」となり再生することができません。
もしよろしければ対応をお願いします。

**Comment by kphrx** [comment]
domand対応時にdアニメストアの読み込み部分の対応が漏れていたようです。報告ありがとうございます

**Comment by nonamestreamer** [comment]
早速のご対応ありがとうございます。
アップデートしてみたのですがアプデ前と変わらず「この動画は有料です」と表示されてしまいます。
実行環境は以下になります。
chrome:131.0.6778.205
Tampermonkey:5.3.3
MylistPocket:0.5.15-fix-mylist-api.7
ZenzaWatch DEV版 fix playlist:2.6.3-fix-playlist.45
ZenzaWatch HLS Support:0.0.22-kphrx-patch.4
dアニメストア ニコニコ支店には入会済みで期限の切れた動画の公式プレイヤーからはからdアニメストアの動画に遷移することは出来ます。

**Comment by kphrx** [comment]
確認ありがとうございます。そもそもdアニメに置き換える機能を修正していた #7 の時点で機能しない記述をしていました。ありがとうございます

**Comment by nonamestreamer** [comment]
度々申し訳ございません。
ZenzaWatch DEV版 fix playlist:2.6.3-fix-playlist.46
にアップデートしたのですが以下のようにエラーが発生してしまいます。
![image](https://github.com/user-attachments/assets/fdf3816c-acc8-4053-95e5-ed0e9341a7b1)

**Comment by kphrx** [comment]
@nonamestreamer `playlist-deploy-fix-danime`ブランチに `2.6.3-fix-playlist.46.1` にして設置してみました。下記リンクから直接インストールできるので動作していればお知らせください。

https://github.com/kphrx/ZenzaWatch/raw/playlist-deploy-fix-danime/dist/ZenzaWatch-dev.user.js

**Comment by nonamestreamer** [comment]
無事動作していることを確認いたしました。
こちらから立て続けにお願いをしてしまったにもかかわらず迅速に対応していただきありがとうございました。
